apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/labsio/homelab.git
    targetRevision: HEAD
    path: k8s/apps/linkding/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: linkding
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
