name: Lint YAML files

on:
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint --quiet

      - name: Run yamllint
        run: yamllint -d relaxed .
